### PR TITLE
Removed glass rect. Fixed events for scrubber.

### LINKED ISSUE #270: adding click event
Hi,

I am trying to add drill down functionality to my chart.
What I mean is when the use clicks on a bar (or point) ill reload the chart with different 'lower level' data.
I am using tooltip modes 'scrubber' as I need to format the x-axis value before displaying it and also we want the tooltip to display above bar/at point which works great. 
The problem ive come up against is that the docs say there is a build in click event but only when not using a tooltip with mode scrubber.

Has anyone solved a similar problem of adding a click event to a chart with tooltip scrubber or any suggestions how to go about doing this?

Thanks
lj1000

### LINKED ISSUE #324: onClick event
According to the readme I can implement custom events such as onClick.
I can't seem to manage to do so, here is an example codepen from one of the example's I've edited a bit:

http://codepen.io/anon/pen/NGqNwP

I don't see any events regarding the click get triggered in the code.

### PR DESCRIPTION
**Pull request by chaosmail**
the most crazy PR since i started with n3-charts.

* Removed the glass rect, improved scrubber (much faster because we bind `mousemove` to `svg` node)
* Enabled all events for all tooltips
* Crazy refactoring of the event and scrubber tests

Here is an example for click and hover in scrubber mode: http://plnkr.co/edit/LByntodp64Dt3m0roAC9?p=preview

Fixes #324
Fixes #270

Best,
Christoph

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
Nice work ! One remark, though : the click/hover events won't fire on anything but the columns, because the line/area dots (or the dots themselves for a dot series) will be hidden by the scrubber...

**Comment by chaosmail** [comment]
yeah, you are right. now it should work ;)

**Comment by chaosmail** [comment]
Alright, I enhanced the tests a little bit and rebased to master

**Comment by lorem--ipsum** [comment]
Dude, this is great work. :poultry_leg:

**Pull request merged**
