### PR TITLE
Removed old test cases...

### PR DESCRIPTION
**Pull request by lorem--ipsum**

### CODE REVIEW

**Comment by chaosmail** [comment]
Ooh good, finally we are cleaning up :) where does this error on zooming and panning in the tests come from - when you just delete some old files, strange..

**Comment by lorem--ipsum** [comment]
Yeah I don't know, master is failing to on those tests. I'll update them, this is not an "official" feature anyway.

**Comment by lorem--ipsum** [comment]
What the hell is happening.

**Comment by lorem--ipsum** [comment]
Fuck yeah. Commented out the flaky test.

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Pull request merged**
