### PR TITLE
Added toggle event for series visibility changes

### PR DESCRIPTION
**Pull request by chaosmail**
Hi n3-chart team,

I added an event `toggle` for listening on visibility changes of the series. I need to also apologize; the proposed naming for events is not really optimal, as if more and more events get added it can become really messy. Therefore, I propose to prefix the events with *on-*, such as 
* `on-click`
* `on-hover`
* `on-focus`
* `on-toggle`

What do you think? In this PR I implement the new names, but I keep also the old names (to be removed in 2.x release). I am also not sure if this convention interferes with default browser events in any other browser besides Chrome and Firefox.

As usual, here is a demo: [http://plnkr.co/edit/Vx4Onpr1WR41ysU4nvs7](http://plnkr.co/edit/Vx4Onpr1WR41ysU4nvs7?p=preview)

Best,
Christoph

### CODE REVIEW

**Comment by chaosmail** [comment]
or maybe instead of the `on-` prefix, we could simply take a `n3-` prefix, such as `n3-click`. What do you think?

**Comment by lorem--ipsum** [comment]
I think the `on-` syntax is great. The `n3-` doesn't bring any actual information : there's no need to tell that the current DOM element is and n3 thing, since the element's tag is already semantic enough, in my opinion. Besides, it looks more "standard" ^^

**Comment by chaosmail** [comment]
yeah, good point. `on-click` looks self-explaining actually

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Pull request merged**
