### PR TITLE
sanitizedNumber now returns a float

### LINKED ISSUE #218: Min and max attribute for axes don't allow decimal values
Hi n3-charts team,

when I try (on the [playground page](http://n3-charts.github.io/line-chart/#/playground?dataType=linear&options=%7B%22lineMode%22:%22cardinal%22,%22tension%22:0.7,%22axes%22:%7B%22x%22:%7B%22type%22:%22linear%22,%22key%22:%22x%22%7D,%22y%22:%7B%22type%22:%22linear%22%7D%7D,%22tooltipMode%22:%22dots%22,%22drawLegend%22:true,%22drawDots%22:true,%22stacks%22:%5B%5D,%22series%22:%5B%7B%22y%22:%22val_0%22,%22label%22:%22This%22,%22type%22:%22area%22,%22color%22:%22%23bcbd22%22,%22axis%22:%22y%22,%22thickness%22:%221px%22,%22visible%22:true,%22dotSize%22:2,%22id%22:%22series_0%22,%22drawDots%22:true%7D,%7B%22y%22:%22val_1%22,%22label%22:%22Is%22,%22type%22:%22column%22,%22color%22:%22%2317becf%22,%22axis%22:%22y%22,%22visible%22:true,%22id%22:%22series_1%22%7D,%7B%22y%22:%22val_2%22,%22label%22:%22Awesome%22,%22color%22:%22%239467bd%22,%22axis%22:%22y%22,%22type%22:%22line%22,%22thickness%22:%221px%22,%22visible%22:true,%22dotSize%22:2,%22id%22:%22series_2%22,%22drawDots%22:true%7D%5D,%22tooltip%22:%7B%22mode%22:%22scrubber%22%7D,%22columnsHGap%22:5%7D) ) to input decimal values for the min and max axes-attributes, it automatically removes the decimal point and all numbers behind the decimal point. So it's currently not possible to put decimal values to min and max.

Is there any possibility, to make this work?

Best,
Christoph

### PR DESCRIPTION
**Pull request by chaosmail**
Hi n3-charts team,

I modified the sanitizedNumber function in the options to return a float instead of an integer. This allows float values in options such as min and max.

Fixes #218

Best,
Christoph

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
Hi !

Could you add a test to make sure this change is not overwritten by mistake down the road ?

Thanks :-)

**Comment by chaosmail** [comment]
sure, here it is

**Comment by lorem--ipsum** [comment]
Great, thanks ! Can you rebase on master so I can merge this please ?

**Comment by chaosmail** [comment]
here is the rebased and rebuilt PR. i will rebase the other ones, after this has been merged.

**Comment by lorem--ipsum** [comment]
Awesome.

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Pull request merged**
