### PR TITLE
Added clipSeries option to clip the content area of the chart

### LINKED ISSUE #120: Great Stuff! But how do I clip extra lines below 0!
Hi,

I am finally getting up to speed with said graphs. They are great.

I wanted to know why when the y data value==0, linechart draws below the axis?
My values are always 0 or more.
Is the a way to tell linechart to not darw below the x-axis?

Pics added for context.
musicbox

Thanks in advance,

Jacques

### PR DESCRIPTION
**Pull request by chaosmail**
Hi Sébastien,

I added a `clipSeries` option for the chart to clip the content area of the chart in case it moves out of the chart area. This happens usually when interpolation is enabled, e.g. `lineMode` is set to 'cardinal'.

I needed to add an uuid per chart, because the clip-paths are defined with an url; and it has to be a unique clip-path per chart. No worries, I added tests :)

Here is a demo [http://plnkr.co/edit/HjWFhmSyYwkyqGZXMimK](http://plnkr.co/edit/HjWFhmSyYwkyqGZXMimK?p=preview)

Fixes #120 

Best,
Christoph

### CODE REVIEW

**Comment by chaosmail** [comment]
Maybe we find a better name than `clipSeries`

**Comment by lorem--ipsum** [comment]
Hey, thanks for the PR ! Maybe we could go with something derived from CSS, like `hideOverflow: true` ?

**Comment by chaosmail** [comment]
Good idea :) should we specify somehow that we mean the content-area or should this be clear?

**Comment by lorem--ipsum** [comment]
Hmmmm I guess it'll be good for now, we'll see if users find that confusing ^^

**Comment by chaosmail** [comment]
alright

**Comment by chaosmail** [comment]
just trying to write an explanation for the README. What about this?

If `hideOverflow` is set to `true`, the series will be clipped to the chart area.

**Comment by lorem--ipsum** [comment]
Yeah, this looks good. Maybe you can also include a reference to the issue ?

**Comment by lorem--ipsum** [comment]
Dammit, I think you need to rebase again, I changed the README file in your back, sorry :-)

**Comment by chaosmail** [comment]
no worries, here is the rebase

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Pull request merged**
