### PR TITLE
Fixed endless digest bug

### PR DESCRIPTION
**Pull request by lorem--ipsum**
Fixes an endless digest loop (found when working on gh-pages...).

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
@chaosmail could you take a look and merge this please ?

**Comment by chaosmail** [comment]
Looks good! I just wonder if this $watchCollection really solve the digest loop problem? I haven't used it that often but reading through [http://stackoverflow.com/a/29189252](http://stackoverflow.com/a/29189252) it should not make a big difference.

**Comment by lorem--ipsum** [comment]
I'm pretty sure it does, since I tried live (I was working on gh-pages and live-debugged before actually creating a branch and submitting a PR). Unfortunately I didn't know how to reproduce that...

About the differences between `$watch` and `$watchCollection`, I think that `$scope.$watch('[a, b, c]'...` is just not correct syntax. Either we're supposed to use the `+` syntax, or the `$watchCollection` to observe several variables at once. Here's a CodePen that demonstrates the bug : http://codepen.io/lorem--ipsum/pen/mJOxGV

:-)

**Comment by chaosmail** [comment]
thanks for clarifying :)

If you use $watch and set the objectEquality argument to `true` it doesn't cause an infinite digest in your demo. 

```javascript 
$scope.$watch('[a, b, c]', function(values) {
    $scope.results.push('$watch', values);
  }, true);
```

However, $watchCollection is the proper way of watching several arguments it since AngularJS 1.1.4, but I think mainly for performance improvements :)

**Pull request merged**
