### PR TITLE
Added innerTicks and grid

### LINKED ISSUE #195: Ability to draw horizontal grid lines?
Not an issue as much as a request: I have been looking without resolve for a way to add horizontal grid lines or possibly extend the exiting ticks to be the width of the graph.  Is this possible and if so can you direct me to the line number I might update that ability?

### LINKED ISSUE #300: Enable tick marks on the axes
Scientific figures just don't look good without them.

### PR DESCRIPTION
**Pull request by chaosmail**
Hi Sébastien,

finally I had some time to implement `innerTicks` and `grid` which can be both activated in the axes options.

Here is a demo: http://plnkr.co/edit/7IYKfdegKCseLBmJgrbv?p=preview

Fixes #300
Fixes #195

Best,
Christoph

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
It looks great man ! If I find some time I'll add a visual test as well.

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Comment by marshall007** [comment]
@chaosmail I was just playing around with this and noticed if you set `grid: true` on the x-axis then the grid is overlaid on top of the existing y-axes lines (so they appear grey). Updated your plnkr to demonstrate this:

http://plnkr.co/edit/VP99gY5MrfBKd90DaRQB?p=preview

**Comment by chaosmail** [comment]
thanks a lot for reporting this; i saw also that the grid is not updating when zooming.

**Pull request merged**
