### PR TITLE
Added mouse events `mouseenter`, `mouseover` and `mouseout` and some fixes

### LINKED ISSUE #285: Wrong date range displayed when array of dates has only one item
If only one item of type Date is presented in $scope.data the x-axis doesn`t show it but instead shows weird date range of year 1980 to 2060.

A few examples of code:
http://jsfiddle.net/n5qsgb9e/3/
http://codepen.io/anon/pen/GJwdKy

### LINKED ISSUE #297: Notify hover on and off
Hi, First and foremost great project!
I wanted to know if the following is possible:
I have a chart displaying the height graph of a cycling route.
the route is displayed on a map next to the chart.
I would like the user to be able to hover on the chart and while doing so the relevant map location would be highlighted as well.
so basically what I need is hover-in, hover-out and hover-changed, is there anything like it currently?

### LINKED ISSUE #313: If several charts are presented on page zoom-reset-icon is shown only on first one.
If several charts are presented on page zoom-reset-icon is shown only on first one.

### LINKED ISSUE #314: duplication of labels in the X axis
Given this data
```
[{"235":72.85,"x":"2015-08-27T07:00:00.000Z"}]
```

and this options setup:
```
        $scope.options = {
          margin: {
            right: 30,
            top: 20,
          },
          stacks: [{
            axis: "y",
            series: labels.map(function(obj) {
              return obj.name;
            })
          }],
          axes: {
            x: {
              zoomable: false,
              type: 'date',
              ticksFormat: '%B',
              ticks: d3.time.months,
              ticksRotate: 0
            },
            y: {
              zoomable: true,
              ticksFormat: '.2f',
              ticks: 5,
              min: 0
            }
          },
          tooltip: {
            mode: 'scrubber',
            formatter: function(x, y, series) {

              return moment(x).format("Do MMM, dddd") + " " + y + " " + series.label;
            }
          },
          lineMode: "cardinal",
          series: series,
          columnsHGap: 0,
        }
```
I experience this weird repetition in the x axis labels space

screen shot 2015-08-28 at 6 49 44 pm

### PR DESCRIPTION
**Pull request by chaosmail**
I added a few more mouse events, and the additional `series` argument for the event listeners.
Here is a demo: http://plnkr.co/edit/b1HRnyeV08tjpO97qN4n?p=preview

Fixes #297
Fixes #313 
Fixes #314
Fixes #285

Best,
Christoph

### CODE REVIEW

**Comment by chaosmail** [comment]
I also fixed "Wrong date range displayed when array of dates has only one item" and "reset icon" issues.

**Comment by chaosmail** [comment]
@lorem--ipsum would be great if you could take a look at this and we publish a new version (I could try this if you want).
Best.
Christoph

**Comment by lorem--ipsum** [comment]
Awesome ! :poultry_leg:

**Comment by lorem--ipsum** [comment]
@chaosmail feel free to release :-)

**Pull request merged**
