### PR TITLE
Fixed unit tests to work with Chrome browser

### PR DESCRIPTION
**Pull request by chaosmail**
Hi n3-charts team,

Here is a PR that fixes the unit tests to also work in Chrome.

Best,
Christoph

### CODE REVIEW

**Comment by sebastien-fragnaud** [comment]
Wow this looks great, thanks fro your contribution !

**Comment by chaosmail** [comment]
Hmm the tests were passing on my Linux (FF 38), apparently Travis runs FF 30. I will have to check this again.

**Comment by lorem--ipsum** [comment]
This can be updated in the `travis.yml` file.

**Comment by chaosmail** [comment]
Fixes #158

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Comment by chaosmail** [comment]
Also here, #158 was not closed automatically - I think I should have referenced the issues in the first comment. sorry for that

**Pull request merged**
