### PR TITLE
Added ticksInterval option

### LINKED ISSUE #146: Adding an interval option to an axis on "date" mode
Hello again! I'm loving your library BTW!

I needed to control the interval of one of the axis to show every single day. I did a simple modification on the linechart.js to solve my situation, but I think it would bee nice to have it as an option on the library.

The line I modified was: 
```javascript
1097 - xAxis = d3.svg.axis().scale(x).orient('bottom').ticks(d3.time.days, axesOptions.x.interval).tickFormat(axesOptions.x.labelFunction);
```

and my code ended up like this:
```javascript
axes: {
			x: {
				type: "date", 
				key: "x", 
				labelFunction:xFunction,
				interval:1 
			}
}
```

Right now it only handles days, but I could modify it to be more open and humanize the options ("daily","weekly", "etc") if you are interested.

### PR DESCRIPTION
**Pull request by chaosmail**
Hi Sébastien,

I added a ticksInterval option to define the step size for tick values when a range function (e.g. d3.time.minute) is used. Here is a demo [http://plnkr.co/edit/XB3rQsn6KeDx6juNIzvz](http://plnkr.co/edit/XB3rQsn6KeDx6juNIzvz?p=preview)

Fixes #146

Best,
Christoph

### CODE REVIEW

**Comment by chaosmail** [comment]
here is the rebase ;)  sorry for the weird commit log, somehow git did a merge and I had to commit again

**Comment by lorem--ipsum** [comment]
Could you `rebase -i` to squash the extra commits ? Ping me on gitter if you don't know how to proceed, I'll walk you through it.

**Comment by chaosmail** [comment]
Cool, I didn't know that I can do this also after a new commit to clean the PR

**Comment by sebastien-fragnaud** [comment]
Yeah, that's pretty cool. The only drawback is that you have to force-push, so it's not really adapted to collaborative work, I think. But when working alone on a branch and to do a little cleaning before submitting a PR, I think that's legit.

**Comment by lorem--ipsum** [comment]
Yeah, that's pretty cool. The only drawback is that you have to force-push, so it's not really adapted to collaborative work, I think. But when working alone on a branch and to do a little cleaning before submitting a PR, I think that's legit.

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Pull request merged**
