### PR TITLE
Added zoom trigger key and access to raw value for tooltip hook

### PR DESCRIPTION
**Pull request by chaosmail**
Hi Sebastien,

I made a few changes that I needed for my last project, mainly better customization for zoom and tooltips. Zoom option now supports a `key` property to define the trigger key for the zoom. (On Chrome on Linux, the altKey always triggered the Chrome Menu and hence I had to use shiftKey instead.)

In the tooltipHook, one can now access the raw values of the dataset (and not only the parsed `x`, `y0` and `y1` values), which makes it much easier to customize it.

The series `id` option is not mandatory, however changing visibility fails when the property is missing. I fixed this problem as well.

I also added some documentation.

This is only a draft, and I would love to get your feedback on these options.

Best,
Christoph

PS: I made a couple of more changes for better rendering on hidden elements. I will push these changes soon as well, I just need to write some tests.

### CODE REVIEW

**Comment by chaosmail** [comment]
Oh my dear travis, I get the same typescript lint errors on my local machine, however I have no idea whats going on with `e2e:test:angularjs`.

**Comment by lorem--ipsum** [comment]
I think those changes are okay, however please be aware that you'll need to port them in the new version as well. Feel free to merge and release when Travis passes :-)

**Comment by chaosmail** [comment]
Alright tests are passing, however I bumped node version to 4.0.0 in travis.

**Comment by chaosmail** [comment]
The series `id` option is not mandatory, however changing visibility fails when the property is missing. I fixed this problem as well. I also updated the tests for missing series id.

**Comment by chaosmail** [comment]
Alright @lorem--ipsum, I think now I am good with this one. Will merge soon.

**Pull request merged**
