### PR TITLE
Adding the ability to define the radius of the dots Resolves #485

### LINKED ISSUE #485: Different dots
Is it possible to draw entirely different dots, maybe even squares, or circles within circles (I work with a picky visual designer). In other words, is it possible to alter the dots beyond what is possible with CSS styling? This would also apply to the radius of the dots.

### PR DESCRIPTION
**Pull request by hambyiii**
The dot radius for both the path and the tooltip can be set via the options object with the following format:
```
dots {
  pathRadius: 4,
  tooltipRadius: 6
}
```
If this is not set, it will default to 2 and 3 respectively

### CODE REVIEW

**Comment by hambyiii** [comment]
@lorem--ipsum The build is currently failing due to missing google-chrome-stable dependencies. I don't think that this could be related to my changes. Any advice?

**Comment by lorem--ipsum** [comment]
Okay so I've fixed the issue, please pull master and rebase from it
then push again on your PR's branch and you should be all set

**Comment by lorem--ipsum** [comment]
Please rebase

**Comment by hambyiii** [comment]
Any chance of this getting a review? Would be awesome, since I am currently using a non-official version of the line-chart lib (one with my changes).

**Comment by lorem--ipsum** [comment]
Okay could you please add a e2e test and update the doc so we can see better what'd be the API now ?

Hint : to add an e2e tests, simply run `gulp new-e2e-test --name=my_awesome_test`.

**Comment by hambyiii** [comment]
sure thing

**Comment by hambyiii** [comment]
e2e tests and updated docs, as requested. :)

**Comment by chaosmail** [comment]
Just a quick question on this, why not use CSS to achieve this? Something like
```
circle.dot {
    r: 10px;
}
```
You can play around with an example here: http://codepen.io/chaosmail/pen/bpZBob
In my opinion this setting would only make sense on a per series basis (in some use-cases), but just for styling all dots it's more convenient with CSS. What do you guys think?

**Comment by chaosmail** [comment]
What I like about the v2 is that it is fully customizable via CSS. So I think everything concerning styling that is not based on special series or data points (such as defining radius with a functon of the value) should be added as CSS and not as an option. But I would be happy to discuss this.

**Comment by lorem--ipsum** [comment]
Yeah I agree. I had this feeling yesterday without being able to exactly put my finger on it, but yeah, doing this via CSS makes more sense. How does that sound @hambyiii ?

**Comment by hambyiii** [comment]
Although it is possible to set the dot series via CSS, the same isn't true of the tooltip dot, since that is a path rather than a circle.

**Comment by lorem--ipsum** [comment]
Fair point. Then I think it would make more sense to change the tooltip dots to be circles. Originally I wanted them to be paths so they could have different shapes, but since it's never been done _and_ it's in the way, feel free to change that.

Sorry for being picky, we really appreciate your interest in the project :-)

**Comment by chaosmail** [comment]
Yu can try my demo, it works also for tooltip dots (although a little differently)

**Comment by hambyiii** [comment]
Wrong dots :) I was referring to the actual dot that appears on the chart during mouseover, but as lorem--ipsum says, changing it to a circle and then doing everything via css might be the better solution

**Comment by hambyiii** [comment]
I'm still here, not gone away :) I am going to start a new branch for switching the tooltip dot from a path to a circle, if this is okay with you guys.

**Comment by lorem--ipsum** [comment]
That's great, thanks :)

**Comment by hambyiii** [comment]
Closing this pull request in favour of the new one I have created: https://github.com/n3-charts/line-chart/pull/505

**Pull request closed without merging**
