### PR TITLE
Added stacks description and tests

### PR DESCRIPTION
**Pull request by chaosmail**
The title says it all. Much needed description of `stacks` in the Readme, as well as tests for the previously implemented fix.

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
Could you rebase on master please ?

**Comment by chaosmail** [comment]
here is the rebase :horse_racing:

**Comment by chaosmail** [comment]
rebased to `master`

**Comment by lorem--ipsum** [comment]
:poultry_leg:

**Pull request merged**
