### PR TITLE
Awesome styles simplification

### PR DESCRIPTION
**Pull request by chaosmail**
no more words needed

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
Hey ! Okay I like it, but I think there are too many layers... The static method on `Default` hasn't any actual purpose in my opinion. Why not just have this class override protected properties ? The colors, of course, and other styling bits, but also a `style` object (which could also be called definition, or something else) instead of having the need to instanciate an object through a static method ?

**Comment by chaosmail** [comment]
Yeah absolutely agree, this style classes should be as stupid and lightweight as possible. I started with a simple variable first, but then ended up making it a class for various reasons. But of course, we should do it exactly as you proposed

**Comment by chaosmail** [comment]
what about calling this property `template`?

**Comment by lorem--ipsum** [comment]
Yeah, sounds good !

**Comment by chaosmail** [comment]
yeah, it looks super nice now :D

**Comment by lorem--ipsum** [comment]
Dude, I think we're accidentally reinventing CSS. ^^ Merging it anyway.
:poultry_leg:

**Comment by chaosmail** [comment]
haha, yeah i thought about plugging in less syntax, but then I said naaaa, CSS is alright

**Comment by chaosmail** [comment]
I would like to have an option, that says `template`, `theme` or sth. where the user can define the template for the chart. additionally I want to expose a style attr on the directive to override all style parameters, like `color` etc.

**Comment by chaosmail** [comment]
actually all of this, for not needing another dependency :D

**Pull request merged**
