### PR TITLE
Issue #320 fix

### PR DESCRIPTION
**Pull request by PoOoZaQ**
Add hasOwnProperty to every for..in loop

### CODE REVIEW

**Comment by chaosmail** [comment]
Hi @PoOoZaQ 
thanks a lot for implementing the fix.

I just have some small remarks in order to merge this PR:
* please add your code in the corresponding `src` directory, afterwards run `grunt` to automatically generate the build files
* please use parenthesis for wrapping the if conditions like ` if () { continue }` instead of  `if () continue;`
* Please squash the commits to a single one with a descriptive commit message

if you need help on any of the above steps, please let me know!

Best,
Christoph

**Comment by PoOoZaQ** [comment]
Ran `grunt` and added the parenthesis. Not sure if did the squashing properly, let me know if need to fix something. Thanks

**Comment by chaosmail** [comment]
hmm, it seems that there are no changes in this PR except the dates in the build files (generated by grunt). You can switch to the "Files changed" view to see the changes of your PR. Are you sure you made the changes in the `src` directory?

**Comment by PoOoZaQ** [comment]
Erm sorry my first time working with Github and Grunt.
I made the fixes in build\line-chart.js, compiled the minified, and then ran grunt on the project's folder.
Anything in that procedure is wrong?

**Comment by chaosmail** [comment]
no worries, I am glad your first PR on Github is for n3-line-chart :)

**Comment by chaosmail** [comment]
you should never manually touch the `build` directory, all files inside are generated by the task runner grunt. You should modify files in the `src` directory (coffeescript), these files will then be compiled to JavaScript, concatenated and minified.

**Comment by chaosmail** [comment]
so anything modified in the build dir will be overwritten once you run grunt

**Comment by PoOoZaQ** [comment]
So, I've taken the file from the build dir, modified it and saved it in the src dir, but still gets overwritten when I run grunt

**Comment by chaosmail** [comment]
The changes should be done in the `src/utils/scrubber.coffee` file (this one https://github.com/n3-charts/line-chart/blob/d2f01bbe9fa0f13f969e25b17e6616994c68164c/src/utils/scrubber.coffee)

**Comment by PoOoZaQ** [comment]
Hope its ok now

**Comment by chaosmail** [comment]
Almost there ;)
There are some `*.js` files in the `src` directory that don't belong there. Actually there should be no `*.js` file in this directory. Would be great if you could remove them!

Best,
Christoph

**Comment by chaosmail** [comment]
this one looks good now :) great work! If you could just squash the commits into a single one, this would be very helpful for the commit history. Here is a guide how to do this: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes

**Comment by PoOoZaQ** [comment]
Heya, I've squashed the commits and force-pushed them, I still see 4 separate commits though, so either I need another step or I'm not looking in the right place.
Btw, thanks for the patience and the soft touch, I realize this might be a bit frustrating for you :)

**Comment by chaosmail** [comment]
Hi @PoOoZaQ 
1) don't worry, this takes time. it's been not that long that I was in your position :) and with every little step you are learning and you will get faster
2) nice, I see there is one commit left - perfect. Now we have another problem, that the merged a lot of other stuff into the master. So you would need to rebase your branch on the master branch. Let me know if you need help with this.
Best,
Christoph

**Comment by chaosmail** [comment]
btw. we have arrived now at point 20 on this list:
https://github.com/n3-charts/line-chart/wiki/Contribution

so you see we are almost there ;)

**Comment by chaosmail** [comment]
Hi @PoOoZaQ 
I will close this as it is a little bit outdated. I would recommend you to look into the source of the latest version; it is very clean, well organized and written completely in TypeScript.
Best, Christoph

**Pull request closed without merging**
