### PR TITLE
Added area drawing

### PR DESCRIPTION
**Pull request by lorem--ipsum**

### CODE REVIEW

**Comment by chaosmail** [comment]
man you are on fire :fire:

**Comment by lorem--ipsum** [comment]
Naah, this one was easier :-)

**Comment by chaosmail** [comment]
haha, nice; I have loads of work until Thursday so I will not be able to merge this until then.

**Comment by lorem--ipsum** [comment]
No problem !

**Comment by chaosmail** [comment]
Awesome, very nice work! if we can resolve the `Failed to parse string` this is ready to merge.

**Pull request merged**
