### PR TITLE
Added zooming and panning feature

### LINKED ISSUE #167: Zoom and drag support
Is there any plan to support zoom and drag in this component?

### PR DESCRIPTION
**Pull request by chaosmail**
Hi Sebastien.

I added zooming and panning support, that can be enabled with the `zoomable` property in the axes options. It's recommended to also set `hideOverflow` to `true`.
Here is an example: http://plnkr.co/edit/ewHIITSFoHfIXDxEN7tp?p=preview

Fixes #167

Best,
Christoph

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
Wow, nice work ! Is there a way to reset the zoom and pan to default ?

**Comment by chaosmail** [comment]
good point, there is no option for this right now. would be great if we could display a little icon once we have scrolled to reset to the original view. however, i am super bad in designing such an icon. what do you think? could you make such an icon for me?

**Comment by chaosmail** [comment]
a double click is triggering a zoom into the chart (automatically handled by `d3.bevavior.zoom`) so this action is already taken :/

**Comment by lorem--ipsum** [comment]
dammit... I don't really have time to hack an icon right now, unfortunately...

**Comment by chaosmail** [comment]
dont worry, then i will take a look on other chart solutions for zooming and propose sth ;)

**Comment by chaosmail** [comment]
what about this icon?
http://raphaeljs.com/icons/#zoomout

**Comment by lorem--ipsum** [comment]
Yeah, or a simple label with 'reset' could work, too :-)

**Comment by chaosmail** [comment]
I made a proposal, please let me know what you think
http://plnkr.co/edit/ewHIITSFoHfIXDxEN7tp?p=preview

**Comment by lorem--ipsum** [comment]
Yep, that's great ! The unit tests have failed, however, no idea why o_O

**Comment by chaosmail** [comment]
yeah, I didn't add tests yet for the zooming icon and I added a focus container to the chart. This is making some current tests fail - I will correct this tonight ;)

**Comment by lorem--ipsum** [comment]
Awesome !

2015-08-04 10:48 GMT-07:00 chaosmail <notifications@github.com>:

**Comment by chaosmail** [comment]
Now the tests are passing :horse_racing:

**Comment by lorem--ipsum** [comment]
Awesome !

**Pull request merged**
