### PR TITLE
Added log axis

### PR DESCRIPTION
**Pull request by lorem--ipsum**

### CODE REVIEW

**Comment by chaosmail** [comment]
Amazing, you are on fire. This code looks super clean and good ;)

**Comment by chaosmail** [comment]
i like the `scale.range()[0]` thing

**Comment by lorem--ipsum** [comment]
Heh, thanks, that's because log axes don't like 0 values :-)

**Comment by lorem--ipsum** [comment]
@chaosmail wanna merge this ?

**Comment by lorem--ipsum** [comment]
Yay, thanks !

**Pull request merged**
